Computing Returns

In [2]:
import sys
import os
func_lib_path = os.path.abspath(os.path.join(os.getcwd(),''))
sys.path.append(func_lib_path)
import func_lib
import pandas as pd

In [3]:
historical_prices = func_lib.createHistPrices()

In [4]:
historical_prices.head()

,A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,...,WY,WYNN,XEL,XOM,XYL,XYZ,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-03,43.036400,0.838496,NaN,NaN,8.093053,1.215037,NaN,16.274675,27.639874,5.968776,...,10.920059,NaN,6.577459,17.141279,NaN,NaN,4.503595,NaN,25.027779,NaN
2000-01-04,39.748890,0.767802,NaN,NaN,7.861826,1.208433,NaN,14.909401,26.241600,5.906603,...,10.509828,NaN,6.728915,16.812950,NaN,NaN,4.413069,NaN,24.666668,NaN
2000-01-05,37.283260,0.779038,NaN,NaN,7.847376,1.320692,NaN,15.204173,26.624672,5.813338,...,11.066570,NaN,6.988549,17.729519,NaN,NaN,4.435701,NaN,25.138889,NaN
2000-01-06,35.863655,0.711621,NaN,NaN,8.121961,1.307485,NaN,15.328289,25.896820,5.844428,...,11.584243,NaN,6.923642,18.646084,NaN,NaN,4.397982,NaN,23.777779,NaN
2000-01-07,38.852310,0.745330,NaN,NaN,8.208672,1.380124,NaN,16.072985,26.624672,5.937691,...,11.203315,NaN,6.923642,18.591360,NaN,NaN,4.299911,NaN,23.513889,NaN

In [5]:
def computingReturns(historical_prices, list_of_momentums):
    return total_returns

In [6]:
list_of_momentums = [1, 2]

In [ ]:
forecast_horizon = 1
f_returns = historical_prices.pct_change(forecast_horizon)

pandas.DataFrame

In [8]:
f_returns[['AAPL']].head()

                AAPL
Date
2000-01-03       NaN
2000-01-04 -0.084310
2000-01-05  0.014633
2000-01-06 -0.086538
2000-01-07  0.047369

In [10]:
f_returns = f_returns.shift(-forecast_horizon)
f_returns.iloc[:,0:10].head()

,A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM
Date,,,,,,,,,,
2000-01-03,-0.062030,0.014633,NaN,NaN,-0.001838,0.092896,NaN,0.019771,0.014598,-0.015790
2000-01-04,-0.038076,-0.086538,NaN,NaN,0.034991,-0.010000,NaN,0.008163,-0.027337,0.005348
2000-01-05,0.083334,0.047369,NaN,NaN,0.010676,0.055556,NaN,0.048583,0.028106,0.015958
2000-01-06,0.060577,-0.017588,NaN,NaN,-0.007042,0.033493,NaN,0.038610,0.087051,0.000000
2000-01-07,-0.013599,-0.051151,NaN,NaN,-0.014185,0.009259,NaN,-0.068773,-0.041032,-0.015707

In [11]:
f_returns = pd.DataFrame(f_returns.unstack())
name = "F_" + str(forecast_horizon) + "_d_returns"
f_returns.rename(columns={0: name}, inplace=True)
f_returns.head()

              F_1_d_returns
  Date
A 2000-01-03      -0.062030
  2000-01-04      -0.038076
  2000-01-05       0.083334
  2000-01-06       0.060577
  2000-01-07      -0.013599